import "./css/base.css";
import Menu from "../componentes/menu.js"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <header>
          <Menu/>
        </header>
        <main>
          {children}
        </main>
        <footer>
          <p>Author: <strong>Laura Maria Leal Lima</strong></p><br/>
          <p>Using: Next.js</p>
        </footer>     
      </body>
    </html>
  )
}